spring:
  application:
    name: incident-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

tarmac:
  topics:
    incidents-reported: incidents.reported
    incidents-assigned: incidents.assigned
